[Desktop Entry]
Name=Acvamarin
Type=X-GNOME-Metatheme
Comment=

[X-GNOME-Metatheme]
GtkTheme=Acvamarin
MetacityTheme=Acvamarin
IconTheme=Acvamarin
GtkColorScheme=fg_color:#21f6add0ad06,bg_color:#0670275d2024,text_color:#2aaabda0bccc,base_color:#000050d75ad7,selected_fg_color:#000000000000,selected_bg_color:#24ddb315b248,tooltip_fg_color:#289ebb94bac0,tooltip_bg_color:#020212121515
CursorTheme=default
CursorSize=18
NotificationTheme=slider
