#!/bin/sh
set -e
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/maia /usr/share/icons/parrot-logo-100.png /usr/share/icons/parrot-logo-600.png /usr/share/icons/parrot-logo-black-100.png /usr/share/icons/parrot-logo-black-600.png /usr/share/icons/parrot-logo-black.png /usr/share/icons/parrot-logo.png
fi
# End automatically added section
